---
#Author  Light Gao
#Mailto  gaoliang@asiainfo.com
#Date    20171108

#jdk first
- include: jdkInstall.yaml

#then zookeeper
- include: zookeeperInstall.yaml

#at last, start it
- include: zookeeperStart.yaml
