---
#Author  Light Gao
#Mailto  gaoliang@asiainfo.com
#Date    20171110

#os params
os_time_zone: Asia/Shanghai
os_selinux_conf: /etc/selinux/config
os_ulimit_conf: /etc/security/limits.conf
os_ulimit_num: 20480

#os users info define
os_users:
  light:
    uid: 806
    group: light
    home: /home/light
    passwd: abc123
  xjtest:
    uid: 807
    group: xjtest
    home: /home/xjtest
    passwd: abc123
os_user_list: ['light', 'xjtest']


#yum params
yum_repo_name: centos
yum_on_ftp: true
yum_on_local: false

yum_ftp_url: "ftp://{{ groups.vsftpd[0] }}/pub/{{ yum_repo_name }}"
yum_local_dir: /opt/paas/centos


