---
#Author  Light Gao
#Mailto  gaoliang@asiainfo.com
#Date    20171108

#########jdk configuration
#depends
jdk_version: 1.8.0_102
jdk_src_dir: /opt/paas/jdk{{ jdk_version }}.tgz
jdk_install_dir: /opt

#dependless
jdk_install_home: "{{ jdk_install_dir }}/jdk{{ jdk_version }}"
jdk_tarball: true




#########zookeeper configuration
#depends
zk_version: 3.4.9
zk_src_dir: /opt/paas/zookeeper-{{ zk_version }}.tgz
zk_install_dir: /opt
zk_user: root

#dependless
zk_install_home: "{{ zk_install_dir }}/zookeeper-{{ zk_version }}"
zk_bin_dir: "{{ zk_install_home }}/bin"
zk_conf_dir: "{{ zk_install_home }}/conf"
zk_hosts: "{{ ansible_fqdn }}:{{ zk_client_port }}"
zk_tarball: true
zk_group: "{{ zk_user }}"

#depends
zk_client_port: 2981
zk_com_port: 2982
zk_election_port: 2983

#dependless
zk_data_dir: "{{ zk_install_home }}/data"
zk_log_dir: "{{ zk_install_home }}/log"
zk_ticktime: 2000
zk_init_limit: 5
zk_sync_limit: 2

zk_standalone: false
