---
#Author  Light Gao
#Mailto  gaoliang@asiainfo.com
#Date    20171108

- name: hostname setup
  command: hostnamectl set-hostname {{newname}}
  
- name: timezone setup
  command: timedatectl set-timezone {{os_time_zone}}

- name: time adjust
  shell: rm -f /etc/localtime; ln -s /usr/share/zoneinfo/{{os_time_zone}}  /etc/localtime ; hwclock -r

- name: disable selinux
  shell: sed -i '7c SELINUX=disabled' {{os_selinux_conf}}

- name: getenforce
  command: getenforce
  register: selinux_status

- name: setenforce
  shell : setenforce 0
  when: selinux_status == 'Enforcing'

- name: disable firewall
  command: systemctl disable firewalld.service

- name: stop firewall
  command: systemctl stop firewalld.service

- name: hosts configure
  template:
    src: hosts.j2
    dest: /etc/hosts
    mode: 0644

- name: root ulimit setting
  template:
    src: limits.conf.j2
    dest: /etc/security/limits.conf
    mode: 0644

- name: other user ulimit setting
  shell: sed -i '$a {{item[0]}}  {{item[1]}}  {{item[2]}} {{os_ulimit_num}}' {{os_ulimit_conf}}
  with_nested:
    - "{{os_user_list}}"
    - ['soft', 'hard']
    - ['nofile','nproc']

